# Generated by Django 4.1.5 on 2023-01-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.DeleteModel(
            name='MedicalReport',
        ),
    ]
