# Generated by Django 4.1.5 on 2023-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0002_remove_medicalreport_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
